# Generated by Django 2.2.6 on 2019-10-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=20)),
                ('ch', models.IntegerField()),
                ('obj', models.TextField(max_length=1000)),
                ('docente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('proced', models.TextField(max_length=1000)),
                ('recursos', models.CharField(max_length=100)),
                ('plana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planaula.PlanA')),
            ],
        ),
    ]
